[package]
name = "rescuegrid"
version = "0.1.0"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
movegate = { local = "../movegate" }

[addresses]
rescuegrid = "0x0"
